version: '3'
services:
  app:
    network_mode: host
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
      - ./.env-dev:/usr/src/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1